export default [
  {
    value: '←',
    unicode: 'U+2190',
    name: 'LEFTWARDS ARROW',
    category: 'Simple arrows',
  },
  {
    value: '↑',
    unicode: 'U+2191',
    name: 'UPWARDS ARROW',
    category: 'Simple arrows',
  },
  {
    value: '→',
    unicode: 'U+2192',
    name: 'RIGHTWARDS ARROW',
    category: 'Simple arrows',
  },
  {
    value: '↓',
    unicode: 'U+2193',
    name: 'DOWNWARDS ARROW',
    category: 'Simple arrows',
  },
  {
    value: '↔',
    unicode: 'U+2194',
    name: 'LEFT RIGHT ARROW',
    category: 'Simple arrows',
  },
  {
    value: '↕',
    unicode: 'U+2195',
    name: 'UP DOWN ARROW',
    category: 'Simple arrows',
  },
  {
    value: '↖',
    unicode: 'U+2196',
    name: 'NORTH WEST ARROW',
    category: 'Simple arrows',
  },
  {
    value: '↗',
    unicode: 'U+2197',
    name: 'NORTH EAST ARROW',
    category: 'Simple arrows',
  },
  {
    value: '↘',
    unicode: 'U+2198',
    name: 'SOUTH EAST ARROW',
    category: 'Simple arrows',
  },
  {
    value: '↙',
    unicode: 'U+2199',
    name: 'SOUTH WEST ARROW',
    category: 'Simple arrows',
  },

  {
    value: '↚',
    unicode: 'U+219A',
    name: 'LEFTWARDS ARROW WITH STROKE',
    category: 'Arrows with modifications',
  },
  {
    value: '↛',
    unicode: 'U+219B',
    name: 'RIGHTWARDS ARROW WITH STROKE',
    category: 'Arrows with modifications',
  },
  {
    value: '↜',
    unicode: 'U+219C',
    name: 'LEFTWARDS WAVE ARROW',
    category: 'Arrows with modifications',
  },
  {
    value: '↝',
    unicode: 'U+219D',
    name: 'RIGHTWARDS WAVE ARROW',
    category: 'Arrows with modifications',
  },
  {
    value: '↞',
    unicode: 'U+219E',
    name: 'LEFTWARDS TWO HEADED ARROW',
    category: 'Arrows with modifications',
  },
  {
    value: '↟',
    unicode: 'U+219F',
    name: 'UPWARDS TWO HEADED ARROW',
    category: 'Arrows with modifications',
  },
  {
    value: '↠',
    unicode: 'U+21A0',
    alt: 'cursor, right',

    name:
      'RIGHTWARDS TWO HEADED ARROW',
    category: 'Arrows with modifications',
  },
  {
    value: '↡',
    unicode: 'U+21A1',
    name: 'DOWNWARDS TWO HEADED ARROW',
    category: 'Arrows with modifications',
  },
  {
    value: '↢',
    unicode: 'U+21A2',
    name: 'LEFTWARDS ARROW WITH TAIL',
    category: 'Arrows with modifications',
  },
  {
    value: '↣',
    unicode: 'U+21A3',
    name: 'RIGHTWARDS ARROW WITH TAIL',
    category: 'Arrows with modifications',
  },
  {
    value: '↤',
    unicode: 'U+21A4',
    name: 'LEFTWARDS ARROW FROM BAR',
    category: 'Arrows with modifications',
  },
  {
    value: '↥',
    unicode: 'U+21A5',
    name: 'UPWARDS ARROW FROM BAR',
    category: 'Arrows with modifications',
  },
  {
    value: '↦',
    unicode: 'U+21A6',
    name: 'RIGHTWARDS ARROW FROM BAR',
    category: 'Arrows with modifications',
  },
  {
    value: '↧',
    unicode: 'U+21A7',
    alt: 'depth',
    name: 'DOWNWARDS ARROW FROM BAR',
    category: 'Arrows with modifications',
  },
  {
    value: '↨',
    unicode: 'U+21A8',
    name: 'UP DOWN ARROW WITH BASE',
    category: 'Arrows with modifications',
  },
  {
    value: '↩',
    unicode: 'U+21A9',
    name: 'LEFTWARDS ARROW WITH HOOK',
    category: 'Arrows with modifications',
  },
  {
    value: '↪',
    unicode: 'U+21AA',
    name: 'RIGHTWARDS ARROW WITH HOOK',
    category: 'Arrows with modifications',
  },
  {
    value: '↫',
    unicode: 'U+21AB',
    name: 'LEFTWARDS ARROW WITH LOOP',
    category: 'Arrows with modifications',
  },
  {
    value: '↬',
    unicode: 'U+21AC',
    name: 'RIGHTWARDS ARROW WITH LOOP',
    category: 'Arrows with modifications',
  },
  {
    value: '↭',
    unicode: 'U+21AD',
    name: 'LEFT RIGHT WAVE ARROW',
    category: 'Arrows with modifications',
  },
  {
    value: '↮',
    unicode: 'U+21AE',
    name: 'LEFT RIGHT ARROW WITH STROKE',
    category: 'Arrows with modifications',
  },
  {
    value: '↯',
    unicode: 'U+21AF',
    name: 'DOWNWARDS ZIGZAG ARROW',
    category: 'Arrows with modifications',
  },

  {
    value: '↰',
    unicode: 'U+21B0',
    name: 'UPWARDS ARROW WITH TIP LEFTWARDS',
    category: 'Arrows with bent tips ',
  },
  {
    value: '↱',
    unicode: 'U+21B1',
    name: 'UPWARDS ARROW WITH TIP RIGHTWARDS',
    category: 'Arrows with bent tips ',
  },
  {
    value: '↲',
    unicode: 'U+21B2',
    name: 'DOWNWARDS ARROW WITH TIP LEFTWARDS',
    category: 'Arrows with bent tips ',
  },
  {
    value: '↳',
    unicode: 'U+21B3',
    name: 'DOWNWARDS ARROW WITH TIP RIGHTWARDS',
    category: 'Arrows with bent tips ',
  },

  {
    value: '↴',
    unicode: 'U+21B4',
    alt: 'line feed',
    name: 'RIGHTWARDS ARROW WITH CORNER DOWNWARDS',
    category: 'Keyboard symbols and circle arrows',
  },
  {
    value: '↵',
    unicode: 'U+21B5',
    name: 'DOWNWARDS ARROW WITH CORNER LEFTWARDS',
    category: 'Keyboard symbols and circle arrows',
  },
  {
    value: '↶',
    unicode: 'U+21B6',
    name: 'ANTICLOCKWISE TOP SEMICIRCLE ARROW',
    category: 'Keyboard symbols and circle arrows',
  },
  {
    value: '↷',
    unicode: 'U+21B7',
    name: 'CLOCKWISE TOP SEMICIRCLE ARROW',
    category: 'Keyboard symbols and circle arrows',
  },
  {
    value: '↸',
    unicode: 'U+21B8',
    alt: 'home',
    name: 'NORTH WEST ARROW TO LONG BAR',
    category: 'Keyboard symbols and circle arrows',
  },
  {
    value: '↹',
    unicode: 'U+21B9',

    alt: 'tab, tab with shift',
    name:
      'LEFTWARDS ARROW TO BAR OVER RIGHTWARDS ARROW TO BAR',
    category: 'Keyboard symbols and circle arrows',
  },
  {
    value: '↺',
    unicode: 'U+21BA',
    name: 'ANTICLOCKWISE OPEN CIRCLE ARROW',
    category: 'Keyboard symbols and circle arrows',
  },
  {
    value: '↻',
    unicode: 'U+21BB',
    name: 'CLOCKWISE OPEN CIRCLE ARROW',
    category: 'Keyboard symbols and circle arrows',
  },

  {
    value: '↼',
    unicode: 'U+21BC',
    name: 'LEFTWARDS HARPOON WITH BARB UPWARDS',
    category: 'Harpoons',
  },
  {
    value: '↽',
    unicode: 'U+21BD',
    name: 'LEFTWARDS HARPOON WITH BARB DOWNWARDS',
    category: 'Harpoons',
  },
  {
    value: '↾',
    unicode: 'U+21BE',
    name: 'UPWARDS HARPOON WITH BARB RIGHTWARDS',
    category: 'Harpoons',
  },
  {
    value: '↿',
    unicode: 'U+21BF',
    name: 'UPWARDS HARPOON WITH BARB LEFTWARDS',
    category: 'Harpoons',
  },
  {
    value: '⇀',
    unicode: 'U+21C0',
    name: 'RIGHTWARDS HARPOON WITH BARB UPWARDS',
    category: 'Harpoons',
  },
  {
    value: '⇁',
    unicode: 'U+21C1',
    name: 'RIGHTWARDS HARPOON WITH BARB DOWNWARDS',
    category: 'Harpoons',
  },
  {
    value: '⇂',
    unicode: 'U+21C2',
    name: 'DOWNWARDS HARPOON WITH BARB RIGHTWARDS',
    category: 'Harpoons',
  },
  {
    value: '⇃',
    unicode: 'U+21C3',
    name: 'DOWNWARDS HARPOON WITH BARB LEFTWARDS',
    category: 'Harpoons',
  },

  {
    value: '⇄',
    unicode: 'U+21C4',
    name: 'RIGHTWARDS ARROW OVER LEFTWARDS ARROW',
    category: 'Paired arrows and harpoons',
  },
  {
    value: '⇅',
    unicode: 'U+21C5',
    name: 'UPWARDS ARROW LEFTWARDS OF DOWNWARDS ARROW',
    category: 'Paired arrows and harpoons',
  },
  {
    value: '⇆',
    unicode: 'U+21C6',
    name: 'LEFTWARDS ARROW OVER RIGHTWARDS ARROW',
    category: 'Paired arrows and harpoons',
  },
  {
    value: '⇇',
    unicode: 'U+21C7',
    name: 'LEFTWARDS PAIRED ARROWS',
    category: 'Paired arrows and harpoons',
  },
  {
    value: '⇈',
    unicode: 'U+21C8',
    name: 'UPWARDS PAIRED ARROWS',
    category: 'Paired arrows and harpoons',
  },
  {
    value: '⇉',
    unicode: 'U+21C9',
    name: 'RIGHTWARDS PAIRED ARROWS',
    category: 'Paired arrows and harpoons',
  },
  {
    value: '⇊',
    unicode: 'U+21CA',
    name: 'DOWNWARDS PAIRED ARROWS',
    category: 'Paired arrows and harpoons',
  },
  {
    value: '⇋',
    unicode: 'U+21CB',
    name: 'LEFTWARDS HARPOON OVER RIGHTWARDS HARPOON',
    category: 'Paired arrows and harpoons',
  },
  {
    value: '⇌',
    unicode: 'U+21CC',
    name: 'RIGHTWARDS HARPOON OVER LEFTWARDS HARPOON',
    category: 'Paired arrows and harpoons',
  },

  {
    value: '⇍',
    unicode: 'U+21CD',
    name: 'LEFTWARDS DOUBLE ARROW WITH STROKE',
    category: 'Double arrows',
  },
  {
    value: '⇎',
    unicode: 'U+21CE',
    name: 'LEFT RIGHT DOUBLE ARROW WITH STROKE',
    category: 'Double arrows',
  },
  {
    value: '⇏',
    unicode: 'U+21CF',
    name: 'RIGHTWARDS DOUBLE ARROW WITH STROKE',
    category: 'Double arrows',
  },
  {
    value: '⇐',
    unicode: 'U+21D0',
    name: 'LEFTWARDS DOUBLE ARROW',
    category: 'Double arrows',
  },
  {
    value: '⇑',
    unicode: 'U+21D1',
    name: 'UPWARDS DOUBLE ARROW',
    category: 'Double arrows',
  },
  {
    value: '⇒',
    unicode: 'U+21D2',
    name: 'RIGHTWARDS DOUBLE ARROW',
    category: 'Double arrows',
  },
  {
    value: '⇓',
    unicode: 'U+21D3',
    name: 'DOWNWARDS DOUBLE ARROW',
    category: 'Double arrows',
  },
  {
    value: '⇔',
    unicode: 'U+21D4',
    name: 'LEFT RIGHT DOUBLE ARROW',
    category: 'Double arrows',
  },
  {
    value: '⇕',
    unicode: 'U+21D5',
    name: 'UP DOWN DOUBLE ARROW',
    category: 'Double arrows',
  },
  {
    value: '⇖',
    unicode: 'U+21D6',
    name: 'NORTH WEST DOUBLE ARROW',
    category: 'Double arrows',
  },
  {
    value: '⇗',
    unicode: 'U+21D7',
    name: 'NORTH EAST DOUBLE ARROW',
    category: 'Double arrows',
  },
  {
    value: '⇘',
    unicode: 'U+21D8',
    name: 'SOUTH EAST DOUBLE ARROW',
    category: 'Double arrows',
  },
  {
    value: '⇙',
    unicode: 'U+21D9',
    name: 'SOUTH WEST DOUBLE ARROW',
    category: 'Double arrows',
  },

  {
    value: '⇚',
    unicode: 'U+21DA',
    name: 'LEFTWARDS TRIPLE ARROW',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇛',
    unicode: 'U+21DB',
    name: 'RIGHTWARDS TRIPLE ARROW',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇜',
    unicode: 'U+21DC',
    name: 'LEFTWARDS SQUIGGLE ARROW',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇝',
    unicode: 'U+21DD',
    name: 'RIGHTWARDS SQUIGGLE ARROW',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇞',
    unicode: 'U+21DE',
    alt: 'page up',
    name: 'UPWARDS ARROW WITH DOUBLE STROKE',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇟',
    unicode: 'U+21DF',
    alt: 'page down',
    name: 'DOWNWARDS ARROW WITH DOUBLE STROKE',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇠',
    unicode: 'U+21E0',
    name: 'LEFTWARDS DASHED ARROW',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇡',
    unicode: 'U+21E1',
    name: 'UPWARDS DASHED ARROW',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇢',
    unicode: 'U+21E2',
    name: 'RIGHTWARDS DASHED ARROW',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇣',
    unicode: 'U+21E3',
    name: 'DOWNWARDS DASHED ARROW',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇤',
    unicode: 'U+21E4',
    alt: 'leftward tab',
    name: 'LEFTWARDS ARROW TO BAR',
    category: 'Miscellaneous arrows and keyboard symbols',
  },
  {
    value: '⇥',
    unicode: 'U+21E5',
    alt: 'rightward tab',
    name: 'RIGHTWARDS ARROW TO BAR',
    category: 'Miscellaneous arrows and keyboard symbols',
  },

  {
    value: '⇦',
    unicode: 'U+21E6',
    name: 'LEFTWARDS WHITE ARROW',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇧',
    unicode: 'U+21E7',
    alt: 'shift',
    name: 'UPWARDS WHITE ARROW',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇨',
    unicode: 'U+21E8',
    name: 'RIGHTWARDS WHITE ARROW',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇩',
    unicode: 'U+21E9',
    name: 'DOWNWARDS WHITE ARROW',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇪',
    unicode: 'U+21EA',
    alt: 'caps lock',
    name: 'UPWARDS WHITE ARROW FROM BAR',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇫',
    unicode: 'U+21EB',
    name: 'UPWARDS WHITE ARROW ON PEDESTAL',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇬',
    unicode: 'U+21EC',
    alt: 'lock',
    name:
      'UPWARDS WHITE ARROW ON PEDESTAL WITH HORIZONTAL BAR',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇭',
    unicode: 'U+21ED',
    alt: 'numeric lock',
    name:
      'UPWARDS WHITE ARROW ON PEDESTAL WITH VERTICAL BAR',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇮',
    unicode: 'U+21EE',
    name: 'UPWARDS WHITE DOUBLE ARROW',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇯',
    unicode: 'U+21EF',
    name: 'UPWARDS WHITE DOUBLE ARROW ON PEDESTAL',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇰',
    unicode: 'U+21F0',
    name: 'RIGHTWARDS WHITE ARROW FROM WALL',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇱',
    unicode: 'U+21F1',
    alt: 'home',
    name: 'NORTH WEST ARROW TO CORNER',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇲',
    unicode: 'U+21F2',
    alt: 'end',
    name: 'SOUTH EAST ARROW TO CORNER',
    category: 'White arrows and keyboard symbols',
  },
  {
    value: '⇳',
    unicode: 'U+21F3',
    alt: 'scrolling',
    name: 'UP DOWN WHITE ARROW',
    category: 'White arrows and keyboard symbols',
  },

  {
    value: '⇴',
    unicode: 'U+21F4',
    name: 'RIGHT ARROW WITH SMALL CIRCLE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇵',
    unicode: 'U+21F5',
    name: 'DOWNWARDS ARROW LEFTWARDS OF UPWARDS ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇶',
    unicode: 'U+21F6',
    name: 'THREE RIGHTWARDS ARROWS',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇷',
    unicode: 'U+21F7',
    name: 'LEFTWARDS ARROW WITH VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇸',
    unicode: 'U+21F8',
    name:
      'RIGHTWARDS ARROW WITH VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇹',
    unicode: 'U+21F9',
    name:
      'LEFT RIGHT ARROW WITH VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇺',
    unicode: 'U+21FA',
    name: 'LEFTWARDS ARROW WITH DOUBLE VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇻',
    unicode: 'U+21FB',
    alt: 'function',
    name:
      'RIGHTWARDS ARROW WITH DOUBLE VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇼',
    unicode: 'U+21FC',
    alt: 'relation',
    name:
      'LEFT RIGHT ARROW WITH DOUBLE VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇽',
    unicode: 'U+21FD',
    name: 'LEFTWARDS OPEN-HEADED ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇾',
    unicode: 'U+21FE',
    name: 'RIGHTWARDS OPEN-HEADED ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⇿',
    unicode: 'U+21FF',
    name: 'LEFT RIGHT OPEN-HEADED ARROW',
    category: 'Miscellaneous arrows',
  },

  {
    value: '➔',
    unicode: 'U+2794',
    name: 'HEAVY WIDE-HEADED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },

  {
    value: '➘',
    unicode: 'U+2798',
    name: 'HEAVY SOUTH EAST ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➙',
    unicode: 'U+2799',
    name: 'HEAVY RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➚',
    unicode: 'U+279A',
    name: 'HEAVY NORTH EAST ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➛',
    unicode: 'U+279B',
    name: 'DRAFTING POINT RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➜',
    unicode: 'U+279C',
    name: 'HEAVY ROUND-TIPPED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➝',
    unicode: 'U+279D',
    name: 'TRIANGLE-HEADED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➞',
    unicode: 'U+279E',
    name: 'HEAVY TRIANGLE-HEADED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➟',
    unicode: 'U+279F',
    name: 'DASHED TRIANGLE-HEADED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➠',
    unicode: 'U+27A0',
    name: 'HEAVY DASHED TRIANGLE-HEADED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➡',
    unicode: 'U+27A1',
    name: 'BLACK RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➢',
    unicode: 'U+27A2',
    name: 'THREE-D TOP-LIGHTED RIGHTWARDS ARROWHEAD',
    category: 'Dingbat arrows',
  },
  {
    value: '➣',
    unicode: 'U+27A3',
    name: 'THREE-D BOTTOM-LIGHTED RIGHTWARDS ARROWHEAD',
    category: 'Dingbat arrows',
  },
  {
    value: '➤',
    unicode: 'U+27A4',
    name: 'BLACK RIGHTWARDS ARROWHEAD',
    category: 'Dingbat arrows',
  },
  {
    value: '➥',
    unicode: 'U+27A5',
    name: 'HEAVY BLACK CURVED DOWNWARDS AND RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➦',
    unicode: 'U+27A6',
    name: 'HEAVY BLACK CURVED UPWARDS AND RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➧',
    unicode: 'U+27A7',
    name: 'SQUAT BLACK RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➨',
    unicode: 'U+27A8',
    name: 'HEAVY CONCAVE-POINTED BLACK RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➩',
    unicode: 'U+27A9',
    name: 'RIGHT-SHADED WHITE RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➪',
    unicode: 'U+27AA',
    name: 'LEFT-SHADED WHITE RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➫',
    unicode: 'U+27AB',
    name: 'BACK-TILTED SHADOWED WHITE RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➬',
    unicode: 'U+27AC',
    name: 'FRONT-TILTED SHADOWED WHITE RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➭',
    unicode: 'U+27AD',
    name: 'HEAVY LOWER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➮',
    unicode: 'U+27AE',
    name: 'HEAVY UPPER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➯',
    unicode: 'U+27AF',
    name: 'NOTCHED LOWER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➱',
    unicode: 'U+27B1',
    name: 'NOTCHED UPPER RIGHT-SHADOWED WHITE RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➲',
    unicode: 'U+27B2',
    name: 'CIRCLED HEAVY WHITE RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➳',
    unicode: 'U+27B3',
    name: 'WHITE-FEATHERED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➴',
    unicode: 'U+27B4',
    name: 'BLACK-FEATHERED SOUTH EAST ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➵',
    unicode: 'U+27B5',
    name: 'BLACK-FEATHERED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➶',
    unicode: 'U+27B6',
    name: 'BLACK-FEATHERED NORTH EAST ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➷',
    unicode: 'U+27B7',
    name: 'HEAVY BLACK-FEATHERED SOUTH EAST ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➸',
    unicode: 'U+27B8',
    name: 'HEAVY BLACK-FEATHERED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➹',
    unicode: 'U+27B9',
    name: 'HEAVY BLACK-FEATHERED NORTH EAST ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➺',
    unicode: 'U+27BA',
    name: 'TEARDROP-BARBED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➻',
    unicode: 'U+27BB',
    name: 'HEAVY TEARDROP-SHANKED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➼',
    unicode: 'U+27BC',
    name: 'WEDGE-TAILED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➽',
    unicode: 'U+27BD',
    name: 'HEAVY WEDGE-TAILED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },
  {
    value: '➾',
    unicode: 'U+27BE',
    name: 'OPEN-OUTLINED RIGHTWARDS ARROW',
    category: 'Dingbat arrows',
  },

  {
    value: '⟰',
    unicode: 'U+27F0',
    name: 'UPWARDS QUADRUPLE ARROW',
    category: 'Arrows',
  },
  {
    value: '⟱',
    unicode: 'U+27F1',
    name: 'DOWNWARDS QUADRUPLE ARROW',
    category: 'Arrows',
  },
  {
    value: '⟲',
    unicode: 'U+27F2',
    name: 'ANTICLOCKWISE GAPPED CIRCLE ARROW',
    category: 'Arrows',
  },
  {
    value: '⟳',
    unicode: 'U+27F3',
    name: 'CLOCKWISE GAPPED CIRCLE ARROW',
    category: 'Arrows',
  },
  {
    value: '⟴',
    unicode: 'U+27F4',
    name: 'RIGHT ARROW WITH CIRCLED PLUS',
    category: 'Arrows',
  },

  {
    value: '⟵',
    unicode: 'U+27F5',
    name: 'LONG LEFTWARDS ARROW',
    category: 'Long arrows',
  },
  {
    value: '⟶',
    unicode: 'U+27F6',
    name: 'LONG RIGHTWARDS ARROW',
    category: 'Long arrows',
  },
  {
    value: '⟷',
    unicode: 'U+27F7',
    name: 'LONG LEFT RIGHT ARROW',
    category: 'Long arrows',
  },
  {
    value: '⟸',
    unicode: 'U+27F8',
    name: 'LONG LEFTWARDS DOUBLE ARROW',
    category: 'Long arrows',
  },
  {
    value: '⟹',
    unicode: 'U+27F9',
    name: 'LONG RIGHTWARDS DOUBLE ARROW',
    category: 'Long arrows',
  },
  {
    value: '⟺',
    unicode: 'U+27FA',
    name: 'LONG LEFT RIGHT DOUBLE ARROW',
    category: 'Long arrows',
  },
  {
    value: '⟻',
    unicode: 'U+27FB',
    alt: 'maps from',
    name: 'LONG LEFTWARDS ARROW FROM BAR',
    category: 'Long arrows',
  },
  {
    value: '⟼',
    unicode: 'U+27FC',
    alt: 'maps to',
    name: 'LONG RIGHTWARDS ARROW FROM BAR',
    category: 'Long arrows',
  },
  {
    value: '⟽',
    unicode: 'U+27FD',
    name: 'LONG LEFTWARDS DOUBLE ARROW FROM BAR',
    category: 'Long arrows',
  },
  {
    value: '⟾',
    unicode: 'U+27FE',
    name: 'LONG RIGHTWARDS DOUBLE ARROW FROM BAR',
    category: 'Long arrows',
  },
  {
    value: '⟿',
    unicode: 'U+27FF',
    name: 'LONG RIGHTWARDS SQUIGGLE ARROW',
    category: 'Long arrows',
  },

  {
    value: '⤀',
    unicode: 'U+2900',
    alt: 'surjection',
    name:
      'RIGHTWARDS TWO-HEADED ARROW WITH VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤁',
    unicode: 'U+2901',
    alt: 'finite surjection',
    name:
      'RIGHTWARDS TWO-HEADED ARROW WITH DOUBLE VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤂',
    unicode: 'U+2902',
    name: 'LEFTWARDS DOUBLE ARROW WITH VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤃',
    unicode: 'U+2903',
    name: 'RIGHTWARDS DOUBLE ARROW WITH VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤄',
    unicode: 'U+2904',
    name: 'LEFT RIGHT DOUBLE ARROW WITH VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤅',
    unicode: 'U+2905',
    alt: 'maps to',
    name: 'RIGHTWARDS TWO-HEADED ARROW FROM BAR',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤆',
    unicode: 'U+2906',
    alt: 'maps from',
    name: 'LEFTWARDS DOUBLE ARROW FROM BAR',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤇',
    unicode: 'U+2907',
    alt: 'maps to',
    name: 'RIGHTWARDS DOUBLE ARROW FROM BAR',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤈',
    unicode: 'U+2908',
    name: 'DOWNWARDS ARROW WITH HORIZONTAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤉',
    unicode: 'U+2909',
    name: 'UPWARDS ARROW WITH HORIZONTAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤊',
    unicode: 'U+290A',
    name: 'UPWARDS TRIPLE ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤋',
    unicode: 'U+290B',
    name: 'DOWNWARDS TRIPLE ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤌',
    unicode: 'U+290C',
    name: 'LEFTWARDS DOUBLE DASH ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤍',
    unicode: 'U+290D',
    name: 'RIGHTWARDS DOUBLE DASH ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤎',
    unicode: 'U+290E',
    name: 'LEFTWARDS TRIPLE DASH ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤏',
    unicode: 'U+290F',
    name: 'RIGHTWARDS TRIPLE DASH ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤐',
    unicode: 'U+2910',
    name: 'RIGHTWARDS TWO-HEADED TRIPLE DASH ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤑',
    unicode: 'U+2911',
    name: 'RIGHTWARDS ARROW WITH DOTTED STEM',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤒',
    unicode: 'U+2912',
    name: 'UPWARDS ARROW TO BAR',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤓',
    unicode: 'U+2913',
    name: 'DOWNWARDS ARROW TO BAR',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤔',
    unicode: 'U+2914',
    alt: 'injection',
    name:
      'RIGHTWARDS ARROW WITH TAIL WITH VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤕',
    unicode: 'U+2915',
    alt: 'finite injection',
    name:
      'RIGHTWARDS ARROW WITH TAIL WITH DOUBLE VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤖',
    unicode: 'U+2916',
    alt: 'bijection, bijective mapping',
    name:
      'RIGHTWARDS TWO-HEADED ARROW WITH TAI',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤗',
    unicode: 'U+2917',
    alt: 'notation surjective injection',
    name: 'RIGHTWARDS TWO-HEADED ARROW WITH TAIL WITH VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤘',
    unicode: 'U+2918',
    alt: 'notation finite surjective injection',
    name:
      'RIGHTWARDS TWO-HEADED ARROW WITH TAIL WITH DOUBLE VERTICAL STROKE',
    category: 'Miscellaneous arrows',
  },

  {
    value: '⤙',
    unicode: 'U+2919',
    name: 'LEFTWARDS ARROW-TAIL',
    category: 'Arrow tails',
  },
  {
    value: '⤚',
    unicode: 'U+291A',
    name: 'RIGHTWARDS ARROW-TAIL',
    category: 'Arrow tails',
  },
  {
    value: '⤛',
    unicode: 'U+291B',
    name: 'LEFTWARDS DOUBLE ARROW-TAIL',
    category: 'Arrow tails',
  },
  {
    value: '⤜',
    unicode: 'U+291C',
    name: 'RIGHTWARDS DOUBLE ARROW-TAIL',
    category: 'Arrow tails',
  },

  {
    value: '⤝',
    unicode: 'U+291D',
    name: 'LEFTWARDS ARROW TO BLACK DIAMOND',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤞',
    unicode: 'U+291E',
    name: 'RIGHTWARDS ARROW TO BLACK DIAMOND',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤟',
    unicode: 'U+291F',
    name: 'LEFTWARDS ARROW FROM BAR TO BLACK DIAMOND',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤠',
    unicode: 'U+2920',
    name: 'RIGHTWARDS ARROW FROM BAR TO BLACK DIAMOND',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤡',
    unicode: 'U+2921',
    name: 'NORTH WEST AND SOUTH EAST ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤢',
    unicode: 'U+2922',
    name: 'NORTH EAST AND SOUTH WEST ARROW',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤣',
    unicode: 'U+2923',
    name: 'NORTH WEST ARROW WITH HOOK',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤤',
    unicode: 'U+2924',
    name: 'NORTH EAST ARROW WITH HOOK',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤥',
    unicode: 'U+2925',
    name: 'SOUTH EAST ARROW WITH HOOK',
    category: 'Miscellaneous arrows',
  },
  {
    value: '⤦',
    unicode: 'U+2926',
    name: 'SOUTH WEST ARROW WITH HOOK',
    category: 'Miscellaneous arrows',
  },

  {
    value: '⤧',
    unicode: 'U+2927',
    name: 'NORTH WEST ARROW AND NORTH EAST ARROW',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤨',
    unicode: 'U+2928',
    name: 'NORTH EAST ARROW AND SOUTH EAST ARROW',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤩',
    unicode: 'U+2929',
    name: 'SOUTH EAST ARROW AND SOUTH WEST ARROW',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤪',
    unicode: 'U+292A',
    name: 'SOUTH WEST ARROW AND NORTH WEST ARROW',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤫',
    unicode: 'U+292B',
    name: 'RISING DIAGONAL CROSSING FALLING DIAGONAL',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤬',
    unicode: 'U+292C',
    name: 'FALLING DIAGONAL CROSSING RISING DIAGONAL',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤭',
    unicode: 'U+292D',
    name: 'SOUTH EAST ARROW CROSSING NORTH EAST ARROW',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤮',
    unicode: 'U+292E',
    name: 'NORTH EAST ARROW CROSSING SOUTH EAST ARROW',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤯',
    unicode: 'U+292F',
    name: 'FALLING DIAGONAL CROSSING NORTH EAST ARROW',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤰',
    unicode: 'U+2930',
    name: 'RISING DIAGONAL CROSSING SOUTH EAST ARROW',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤱',
    unicode: 'U+2931',
    name: 'NORTH EAST ARROW CROSSING NORTH WEST ARROW',
    category: 'Crossing arrows for knot theory',
  },
  {
    value: '⤲',
    unicode: 'U+2932',
    name: 'NORTH WEST ARROW CROSSING NORTH EAST ARROW',
    category: 'Crossing arrows for knot theory',
  },

  {
    value: '⤳',
    unicode: 'U+2933',
    name: 'WAVE ARROW POINTING DIRECTLY RIGHT',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤴',
    unicode: 'U+2934',
    name: 'ARROW POINTING RIGHTWARDS THEN CURVING UPWARDS',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤵',
    unicode: 'U+2935',
    name: 'ARROW POINTING RIGHTWARDS THEN CURVING DOWNWARDS',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤶',
    unicode: 'U+2936',
    name: 'ARROW POINTING DOWNWARDS THEN CURVING LEFTWARDS',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤷',
    unicode: 'U+2937',
    name: 'ARROW POINTING DOWNWARDS THEN CURVING RIGHTWARDS',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤸',
    unicode: 'U+2938',
    name: 'RIGHT-SIDE ARC CLOCKWISE ARROW',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤹',
    unicode: 'U+2939',
    name: 'LEFT-SIDE ARC ANTICLOCKWISE ARROW',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤺',
    unicode: 'U+293A',
    name: 'TOP ARC ANTICLOCKWISE ARROW',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤻',
    unicode: 'U+293B',
    name: 'BOTTOM ARC ANTICLOCKWISE ARROW',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤼',
    unicode: 'U+293C',
    name: 'TOP ARC CLOCKWISE ARROW WITH MINUS',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤽',
    unicode: 'U+293D',
    name: 'TOP ARC ANTICLOCKWISE ARROW WITH PLUS',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤾',
    unicode: 'U+293E',
    name: 'LOWER RIGHT SEMICIRCULAR CLOCKWISE ARROW',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⤿',
    unicode: 'U+293F',
    name: 'LOWER LEFT SEMICIRCULAR ANTICLOCKWISE ARROW',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⥀',
    unicode: 'U+2940',
    name: 'ANTICLOCKWISE CLOSED CIRCLE ARROW',
    category: 'Miscellaneous curved arrows',
  },
  {
    value: '⥁',
    unicode: 'U+2941',
    name: 'CLOCKWISE CLOSED CIRCLE ARROW',
    category: 'Miscellaneous curved arrows',
  },

  {
    value: '⥂',
    unicode: 'U+2942',
    name: 'RIGHTWARDS ARROW ABOVE SHORT LEFTWARDS ARROW',
    category: 'Arrows combined with operators',
  },
  {
    value: '⥃',
    unicode: 'U+2943',
    name: 'LEFTWARDS ARROW ABOVE SHORT RIGHTWARDS ARROW',
    category: 'Arrows combined with operators',
  },
  {
    value: '⥄',
    unicode: 'U+2944',
    name: 'SHORT RIGHTWARDS ARROW ABOVE LEFTWARDS ARROW',
    category: 'Arrows combined with operators',
  },
  {
    value: '⥅',
    unicode: 'U+2945',
    name: 'RIGHTWARDS ARROW WITH PLUS BELOW',
    category: 'Arrows combined with operators',
  },
  {
    value: '⥆',
    unicode: 'U+2946',
    name: 'LEFTWARDS ARROW WITH PLUS BELOW',
    category: 'Arrows combined with operators',
  },
  {
    value: '⥇',
    unicode: 'U+2947',
    name: 'RIGHTWARDS ARROW THROUGH X',
    category: 'Arrows combined with operators',
  },
  {
    value: '⥈',
    unicode: 'U+2948',
    name: 'LEFT RIGHT ARROW THROUGH SMALL CIRCLE',
    category: 'Arrows combined with operators',
  },
  {
    value: '⥉',
    unicode: 'U+2949',
    name: 'UPWARDS TWO-HEADED ARROW FROM SMALL CIRCLE',
    category: 'Arrows combined with operators',
  },

  {
    value: '⥊',
    unicode: 'U+294A',
    name: 'LEFT BARB UP RIGHT BARB DOWN HARPOON',
    category: 'Double-barbed harpoons',
  },
  {
    value: '⥋',
    unicode: 'U+294B',
    name: 'LEFT BARB DOWN RIGHT BARB UP HARPOON',
    category: 'Double-barbed harpoons',
  },
  {
    value: '⥌',
    unicode: 'U+294C',
    name: 'UP BARB RIGHT DOWN BARB LEFT HARPOON',
    category: 'Double-barbed harpoons',
  },
  {
    value: '⥍',
    unicode: 'U+294D',
    name: 'UP BARB LEFT DOWN BARB RIGHT HARPOON',
    category: 'Double-barbed harpoons',
  },
  {
    value: '⥎',
    unicode: 'U+294E',
    name: 'LEFT BARB UP RIGHT BARB UP HARPOON',
    category: 'Double-barbed harpoons',
  },
  {
    value: '⥏',
    unicode: 'U+294F',
    name: 'UP BARB RIGHT DOWN BARB RIGHT HARPOON',
    category: 'Double-barbed harpoons',
  },
  {
    value: '⥐',
    unicode: 'U+2950',
    name: 'LEFT BARB DOWN RIGHT BARB DOWN HARPOON',
    category: 'Double-barbed harpoons',
  },
  {
    value: '⥑',
    unicode: 'U+2951',
    name: 'UP BARB LEFT DOWN BARB LEFT HARPOON',
    category: 'Double-barbed harpoons',
  },

  {
    value: '⬀',
    unicode: 'U+2B00',
    name: 'NORTH EAST WHITE ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬁',
    unicode: 'U+2B01',
    name: 'NORTH WEST WHITE ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬂',
    unicode: 'U+2B02',
    name: 'SOUTH EAST WHITE ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬃',
    unicode: 'U+2B03',
    name: 'SOUTH WEST WHITE ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬄',
    unicode: 'U+2B04',
    name: 'LEFT RIGHT WHITE ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬅',
    unicode: 'U+2B05',
    name: 'LEFTWARDS BLACK ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬆',
    unicode: 'U+2B06',
    name: 'UPWARDS BLACK ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬇',
    unicode: 'U+2B07',
    name: 'DOWNWARDS BLACK ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬈',
    unicode: 'U+2B08',
    name: 'NORTH EAST BLACK ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬉',
    unicode: 'U+2B09',
    name: 'NORTH WEST BLACK ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬊',
    unicode: 'U+2B0A',
    name: 'SOUTH EAST BLACK ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬋',
    unicode: 'U+2B0B',
    name: 'SOUTH WEST BLACK ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬌',
    unicode: 'U+2B0C',
    name: 'LEFT RIGHT BLACK ARROW',
    category: 'White and black arrows',
  },
  {
    value: '⬍',
    unicode: 'U+2B0D',
    name: 'UP DOWN BLACK ARROW',
    category: 'White and black arrows',
  },

  {
    value: '⬎',
    unicode: 'U+2B0E',
    name: 'RIGHTWARDS ARROW WITH TIP DOWNWARDS',
    category: 'Arrows with bent tips',
  },
  {
    value: '⬏',
    unicode: 'U+2B0F',
    name: 'RIGHTWARDS ARROW WITH TIP UPWARDS',
    category: 'Arrows with bent tips',
  },
  {
    value: '⬐',
    unicode: 'U+2B10',
    name: 'LEFTWARDS ARROW WITH TIP DOWNWARDS',
    category: 'Arrows with bent tips',
  },
  {
    value: '⬑',
    unicode: 'U+2B11',
    name: 'LEFTWARDS ARROW WITH TIP UPWARDS',
    category: 'Arrows with bent tips',
  },
]
